name: A Esteira Inquebravel

on: push

jobs:
  validar-html:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar o código do repositório
        uses: actions/checkout@v4

      - name: Checar HTML
        run: npx htmlhint "**/*.html"

  validar-css:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar o código do repositório
        uses: actions/checkout@v4

      - name: Checar CSS
        run: npx stylelint "**/*.css"

  preparar-entrega:
    needs: [validar-html, validar-css]
    runs-on: ubuntu-latest
    steps:
      - name: Pegar o código do repositório
        uses: actions/checkout@v4

      - name: Criar pasta dist
        run: mkdir dist